apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.webapp.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      containers:
      - name: {{ .Values.webapp.name }}
        image: {{ .Values.webapp.image }}
        ports:
        - containerPort: 8000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.webapp.name }}-config
              key: Environment
        - name: WebApp__AiApi__BaseUri
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.webapp.name }}-config
              key: BaseUri