apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP