pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .cicd/docker/Dockerfile-titanicai-api
    - .cicd/ado/build-titanicai-api.yaml
    - models/titanicai_model.rds

pr: none

resources:
  repositories:
  - repository: azure-devops-extensions
    type: github
    name: qbituniverse/azure-devops-extensions
    endpoint: qbituniverse

stages:
- stage: DockerBuild
  displayName: 'Build Docker Image'
  variables:
    imageDockerfile: .cicd/docker/Dockerfile-titanicai-api
    imageRepository: qbituniverse/titanicai-api
    imageTag: $(imageVersion).$(Build.BuildId)
    imageVersion: 'N/A'
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Image'
    steps:
    - template: builds/build-assign-number.yaml@azure-devops-extensions
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)

    - template: builds/build-docker.yaml@azure-devops-extensions
      parameters:
        imageRepository: $(imageRepository)
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)