apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
data:
  Environment: {{ .Values.configuration.Environment }}
  BaseUri: {{ .Values.configuration.BaseUri }}