version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    ports:
      - 4000:4000
    volumes:
      - ../../:/usr/src/app
    tty: true
    networks:
      - titanicai.dev

networks:
  titanicai.dev:
    driver: bridge