pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .cicd/docker/Dockerfile-titanicai-webapp
    - .cicd/ado/build-titanicai-webapp.yaml
    - src/webapp/WebApp

pr: none

resources:
  repositories:
  - repository: platformops.dev
    type: github
    name: qbituniverse/platformops.dev
    endpoint: qbituniverse

stages:
- stage: DockerBuildWebapp
  displayName: 'Build Docker Image for Webapp'
  variables:
    imageDockerfile: .cicd/docker/Dockerfile-titanicai-webapp
    imageRepository: qbituniverse/titanicai-webapp
    imageTag: $(imageVersion).$(Build.BuildId)
    imageVersion: 'N/A'
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Image for Webapp'
    steps:
    - template: content/azure-devops/builds/assign-build-number.yaml@platformops.dev
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)

    - template: content/azure-devops/builds/build-push-docker-image.yaml@platformops.dev
      parameters:
        imageRepository: $(imageRepository)
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)
        addLatestTag: true