pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .cicd/dockerfiles/Dockerfile-titanicai-webapp
    - .cicd/ado/build-titanicai-webapp.yaml
    - src/webapp/WebApp

pr: none

resources:
  repositories:
  - repository: azure-devops-extensions
    type: github
    name: qbituniverse/azure-devops-extensions
    endpoint: qbituniverse

stages:
- stage: DockerBuild
  displayName: 'Build Docker Image'
  variables:
    imageDockerfile: .cicd/dockerfiles/Dockerfile-titanicai-webapp
    imageRepository: qbituniverse/titanicai-webapp
    imageTag: $(imageVersion).$(Build.BuildId)
    imageVersion: 'N/A'
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Image'
    steps:
    - template: builds/build-assign-number.yaml@azure-devops-extensions
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)

    - template: builds/build-docker.yaml@azure-devops-extensions
      parameters:
        imageRepository: $(imageRepository)
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)